option_settings:
  aws:elasticbeanstalk:container:nodejs:
    NodeCommand: "npm start"
  aws:elasticbeanstalk:container:nodejs:
    ProxyServer: nginx
  aws:elasticbeanstalk:application:environment:
    NODE_ENV: "production"
  aws:elasticbeanstalk:container:nodejs:
    LogPublicationControl: enabled

commands:
  01_custom_command:
    command: "build_client.sh"